function Group = Crop_SPP_cal(Group,DP)

Group.ele_pv = DP.capacity_pv .* ( 1 - Group.EFF_DECAY) .* Group.TIME_PV * 1000; %MW to kW

Group.salvage = 0.05 * Group.capcost_pv * 0.35;

Group.netprofit = Group.ele_pv .* Group.fit_pv ...
    - DP.qty_water .* Group.price_water ...
    - Group.rent_land...
    - DP.OM_labour...
    - DP.OM_ag...
    - DP.OM_pv;
    
Group.tax = Group.netprofit .* Group.tax_rate;

Group.SPP = (Group.capcost_pv + DP.capcost_ag - Group.salvage)./(Group.ele_pv .* Group.fit_pv + ...
    Group.profit_plant + DP.prod_livestock .* Group.price_livestock...
    + Group.qty_tour .* Group.price_tour + DP.qty_co2 .* Group.price_co2...
    - DP.qty_water .* Group.price_water - Group.rent_land...
    - DP.OM_labour - DP.OM_ag - DP.OM_pv - Group.tax);

end
